#include "ManticoreApp.h"
#include "Moose.h"
#include "AppFactory.h"

template<>
InputParameters validParams<ManticoreApp>()
{
  InputParameters params = validParams<MooseApp>();

  params.set<bool>("use_legacy_uo_initialization") = false;
  params.set<bool>("use_legacy_uo_aux_computation") = false;
  return params;
}

ManticoreApp::ManticoreApp(const std::string & name, InputParameters parameters) :
    MooseApp(name, parameters)
{
  srand(processor_id());

  Moose::registerObjects(_factory);
  ManticoreApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  ManticoreApp::associateSyntax(_syntax, _action_factory);
}

ManticoreApp::~ManticoreApp()
{
}

// External entry point for dynamic application loading
extern "C" void ManticoreApp__registerApps() { ManticoreApp::registerApps(); }
void
ManticoreApp::registerApps()
{
  registerApp(ManticoreApp);
}

// External entry point for dynamic object registration
extern "C" void ManticoreApp__registerObjects(Factory & factory) { ManticoreApp::registerObjects(factory); }
void
ManticoreApp::registerObjects(Factory & factory)
{
}

// External entry point for dynamic syntax association
extern "C" void ManticoreApp__associateSyntax(Syntax & syntax, ActionFactory & action_factory) { ManticoreApp::associateSyntax(syntax, action_factory); }
void
ManticoreApp::associateSyntax(Syntax & syntax, ActionFactory & action_factory)
{
}
